{
  "formatVersion": "1.1",
  "component": {
    "group": "com.erickwok",
    "module": "compose-slidable",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "top.ltfan.multihaptic",
          "module": "multihaptic-compose",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "compose-slidable-metadata-0.1.1.jar",
          "url": "compose-slidable-0.1.1.jar",
          "size": 4052,
          "sha512": "5ef777dc85a693210f23b91396e81c0936e8d94a8a5d589d61a616f33551b3e2a81ff29d14a6640f604904f1e49b96dc535ff197946e253efbd69538e63a6d21",
          "sha256": "56f3c94600e449bf8a4003e3ba4afa0172ff87b23e9933bbe9eb435de8d149f7",
          "sha1": "d04d43b560bc49ab2c746f8a80ba9fe6cd61851d",
          "md5": "e8750cd31d663b094891aa3c32cc69c1"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "compose-slidable-kotlin-0.1.1-sources.jar",
          "url": "compose-slidable-0.1.1-sources.jar",
          "size": 5099,
          "sha512": "303c72abe6adb146c41dc43403101c58f86a42ab43f594e4bd5312e518e3375c8264ab47ed2760e5cc136cbdef140277516c6473cb964fb12fe402c60258b5ef",
          "sha256": "d253d3b5185912cf5af69cfef13795cb80abbca3a3abe323f3644035402a7c72",
          "sha1": "aaa4ac76767cffc4fdf371548b8e4c28d2ef88cd",
          "md5": "c7d2a2cc098c694124637da77afcc76a"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-slidable-android/0.1.1/compose-slidable-android-0.1.1.module",
        "group": "com.erickwok",
        "module": "compose-slidable-android",
        "version": "0.1.1"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-slidable-android/0.1.1/compose-slidable-android-0.1.1.module",
        "group": "com.erickwok",
        "module": "compose-slidable-android",
        "version": "0.1.1"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-slidable-android/0.1.1/compose-slidable-android-0.1.1.module",
        "group": "com.erickwok",
        "module": "compose-slidable-android",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-slidable-iosarm64/0.1.1/compose-slidable-iosarm64-0.1.1.module",
        "group": "com.erickwok",
        "module": "compose-slidable-iosarm64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-slidable-iosarm64/0.1.1/compose-slidable-iosarm64-0.1.1.module",
        "group": "com.erickwok",
        "module": "compose-slidable-iosarm64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-slidable-iosarm64/0.1.1/compose-slidable-iosarm64-0.1.1.module",
        "group": "com.erickwok",
        "module": "compose-slidable-iosarm64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-slidable-iosarm64/0.1.1/compose-slidable-iosarm64-0.1.1.module",
        "group": "com.erickwok",
        "module": "compose-slidable-iosarm64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-slidable-iossimulatorarm64/0.1.1/compose-slidable-iossimulatorarm64-0.1.1.module",
        "group": "com.erickwok",
        "module": "compose-slidable-iossimulatorarm64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-slidable-iossimulatorarm64/0.1.1/compose-slidable-iossimulatorarm64-0.1.1.module",
        "group": "com.erickwok",
        "module": "compose-slidable-iossimulatorarm64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-slidable-iossimulatorarm64/0.1.1/compose-slidable-iossimulatorarm64-0.1.1.module",
        "group": "com.erickwok",
        "module": "compose-slidable-iossimulatorarm64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-slidable-iossimulatorarm64/0.1.1/compose-slidable-iossimulatorarm64-0.1.1.module",
        "group": "com.erickwok",
        "module": "compose-slidable-iossimulatorarm64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-slidable-iosx64/0.1.1/compose-slidable-iosx64-0.1.1.module",
        "group": "com.erickwok",
        "module": "compose-slidable-iosx64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-slidable-iosx64/0.1.1/compose-slidable-iosx64-0.1.1.module",
        "group": "com.erickwok",
        "module": "compose-slidable-iosx64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-slidable-iosx64/0.1.1/compose-slidable-iosx64-0.1.1.module",
        "group": "com.erickwok",
        "module": "compose-slidable-iosx64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-slidable-iosx64/0.1.1/compose-slidable-iosx64-0.1.1.module",
        "group": "com.erickwok",
        "module": "compose-slidable-iosx64",
        "version": "0.1.1"
      }
    }
  ]
}
