platform :ios, '14.0'
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'ComposeSlidableDemo' do
  use_frameworks! :linkage => :static

  pod 'demoShared', :path => '../shared'
end
