{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-slidable/0.1.1/compose-slidable-0.1.1.module",
    "group": "com.erickwok",
    "module": "compose-slidable",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-slidable.aar",
          "url": "compose-slidable-android-0.1.1.aar",
          "size": 54670,
          "sha512": "85c9ebc08beaaa8cc367971652077af001a7015f0838a1ae6894d618629c5fbccd3154270841fc36c2ab46b06a0638299a9dc391cd97ff402505d2081e94c8a1",
          "sha256": "38bc5bcae44629a551526192a17d413905343d854108ae7304daed43b39ac978",
          "sha1": "86ee4166c483488e7b203b2976bac56b0b9856d6",
          "md5": "d4b546860695425a5995e052c036d4b1"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "top.ltfan.multihaptic",
          "module": "multihaptic-compose",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "compose-slidable.aar",
          "url": "compose-slidable-android-0.1.1.aar",
          "size": 54670,
          "sha512": "85c9ebc08beaaa8cc367971652077af001a7015f0838a1ae6894d618629c5fbccd3154270841fc36c2ab46b06a0638299a9dc391cd97ff402505d2081e94c8a1",
          "sha256": "38bc5bcae44629a551526192a17d413905343d854108ae7304daed43b39ac978",
          "sha1": "86ee4166c483488e7b203b2976bac56b0b9856d6",
          "md5": "d4b546860695425a5995e052c036d4b1"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "compose-slidable-android-0.1.1-sources.jar",
          "url": "compose-slidable-android-0.1.1-sources.jar",
          "size": 5099,
          "sha512": "303c72abe6adb146c41dc43403101c58f86a42ab43f594e4bd5312e518e3375c8264ab47ed2760e5cc136cbdef140277516c6473cb964fb12fe402c60258b5ef",
          "sha256": "d253d3b5185912cf5af69cfef13795cb80abbca3a3abe323f3644035402a7c72",
          "sha1": "aaa4ac76767cffc4fdf371548b8e4c28d2ef88cd",
          "md5": "c7d2a2cc098c694124637da77afcc76a"
        }
      ]
    }
  ]
}
